from NanUI.utils import get_font as get_font
from PySide6.QtWidgets import QLayout, QScrollArea, QWidget

class ScrollArea(QScrollArea):
    def __init__(self, parent: QWidget | None = None, font: str | None = None, font_size: int = 12) -> None: ...
    def setContentLayout(self, layout: QLayout) -> None: ...
    def addWidget(self, widget: QWidget) -> None: ...
