from NanUI.utils import get_font as get_font
from NanUI.utils.theme_manager import get_color as get_color
from PySide6.QtCore import QEvent
from PySide6.QtGui import QMouseEvent, QPaintEvent, QResizeEvent, QShowEvent
from PySide6.QtWidgets import QLabel, QLayout, QPushButton, QWidget

class CaptionButton(QPushButton):
    def __init__(self, icon_type: str = 'minimize', parent: QWidget | None = None) -> None: ...
    def set_icon_type(self, icon_type: str) -> None: ...
    def enterEvent(self, event: QEvent) -> None: ...
    def leaveEvent(self, event: QEvent) -> None: ...
    def paintEvent(self, event: QPaintEvent) -> None: ...

class Window(QWidget):
    title_bar: QWidget
    title_label: QLabel
    content_widget: QWidget
    btn_min: CaptionButton
    btn_max: CaptionButton
    btn_close: CaptionButton
    def __init__(self, parent: QWidget | None = None, radius: int = 12, resizable: bool = False) -> None: ...
    def setTitle(self, title: str) -> None: ...
    def setLayout(self, layout: QLayout) -> None: ...
    def event(self, event: QEvent) -> bool: ...
    def mousePressEvent(self, event: QMouseEvent) -> None: ...
    def mouseMoveEvent(self, event: QMouseEvent) -> None: ...
    def mouseReleaseEvent(self, event: QMouseEvent) -> None: ...
    def paintEvent(self, event: QPaintEvent) -> None: ...
    def changeEvent(self, event: QEvent) -> None: ...
    def resizeEvent(self, event: QResizeEvent) -> None: ...
    def showEvent(self, event: QShowEvent) -> None: ...
