from PySide6.QtGui import QFont

DEFAULT_FAMILY: str

def get_font(size: int = 12, weight: QFont.Weight = ..., family: str | None = None, italic: bool = False, underline: bool = False) -> QFont: ...
def get_default_font(size: int = 12) -> QFont: ...
def get_bold_font(size: int = 12) -> QFont: ...
def get_light_font(size: int = 12) -> QFont: ...
