from PySide6.QtWidgets import QApplication, QWidget

THEME_COLORS: dict[str, dict[str, str]]

def get_color(key: str) -> str: ...
def current_theme() -> str: ...
def apply_themed_shadow(widget: QWidget, blur_radius: int = 8, offset_y: int = 1) -> None: ...
def apply_theme(app: QApplication, theme_name: str = 'light') -> bool: ...
